sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - docker-compose build

    - stage: test
      script:
        - yarn test
        - docker-compose run --rm web yarn test:ci

    - stage: deploy
      script: skip
