apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  name: development
data:
  GITHUB_CLIENT_ID: 'd9400d2b53d5f0469ede'
  GOOGLE_CLIENT_ID: '209587178094-tk2sinoh4ssq09bojobdb856ls6gd8ul.apps.googleusercontent.com'
  FACEBOOK_CLIENT_ID: '1651474318250422'

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: development
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 4000

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: development
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: development
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: margaret_api
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
