apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: production
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: production
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: production
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mrgaret/web:latest
        ports:
        - containerPort: 3000
